// Generated by `pnpm brand:assets`; do not edit.
/** Content hashes of the static link previews, for their `?v=` cache-busting parameter. */
export const STATIC_PREVIEW_VERSIONS = { guildbook: "f1f7f4037c", vigil: "134ee63d68" } as const;
