import type { Metadata } from "next";
import { tabardKey } from "@/lib/tabard/config";
import { guildLook, isOrderLook, type LookColumns } from "@/lib/tabard/look";

/** Static brand sets under public/brand (generated by `pnpm brand:assets`). */
export type Brand = "osm" | "guildbook";

/**
 * Where a site's icons and link preview live: a static set under public/brand, or a guild's generated set at
 * /api/brand/{slug}, versioned by its tabard so a new design busts caches.
 */
export interface BrandAssets {
  dir: string;
  version: string | null;
  ogAlt: string;
}

const OG_ALT: Record<Brand, string> = {
  osm: "The Order of Saint Michael tabard, a crimson banner with a gold border and white cross, beside the words Order of Saint Michael, Quis ut Deus.",
  guildbook: "The Guildbook mark, an open gold book with a crimson ribbon, beside the words Guildbook, guild sites for World of Warcraft: Forever.",
};

export function staticBrand(brand: Brand): BrandAssets {
  return { dir: `/brand/${brand}`, version: null, ogAlt: OG_ALT[brand] };
}

/** The Order keeps its static tabard set; other guilds get icons generated from their tabard. */
export function guildBrand(guild: { slug: string; name: string } & LookColumns): BrandAssets {
  if (isOrderLook(guild)) return staticBrand("osm");
  return {
    dir: `/api/brand/${guild.slug}`,
    version: tabardKey(guildLook(guild).tabard),
    ogAlt: `The ${guild.name} tabard beside the guild's name.`,
  };
}

const assets = (b: Brand | BrandAssets) => (typeof b === "string" ? staticBrand(b) : b);

/** The URL of one brand file, e.g. `brandFile(b, "icon-192.png")`. */
export function brandFile(b: Brand | BrandAssets, file: string) {
  const a = assets(b);
  return `${a.dir}/${file}${a.version ? `?v=${a.version}` : ""}`;
}

export function brandIcons(b: Brand | BrandAssets): NonNullable<Metadata["icons"]> {
  return {
    icon: [
      { url: brandFile(b, "icon.svg"), type: "image/svg+xml" },
      { url: brandFile(b, "favicon.ico"), sizes: "48x48" },
    ],
    apple: brandFile(b, "apple-icon.png"),
  };
}

export function brandPreviewImage(b: Brand | BrandAssets) {
  return { url: brandFile(b, "og.png"), width: 1200, height: 630, alt: assets(b).ogAlt };
}

export function brandManifestIcons(b: Brand | BrandAssets) {
  return [
    { src: brandFile(b, "icon-192.png"), sizes: "192x192", type: "image/png", purpose: "any" as const },
    { src: brandFile(b, "icon-512.png"), sizes: "512x512", type: "image/png", purpose: "any" as const },
    { src: brandFile(b, "icon-maskable-512.png"), sizes: "512x512", type: "image/png", purpose: "maskable" as const },
  ];
}

/** Guildbook's public source (AGPL-3.0); both footers link here. */
export const SOURCE_URL = "https://github.com/Guildbook/guildbook";

export const GUILDBOOK_DESCRIPTION =
  "Guild sites for World of Warcraft: Forever. Rosters, applications, raid schedules, progression and combat log reviews, on your own subdomain.";
