import { CREST_MANIFEST } from "@/lib/tabard/crest-manifest";

/**
 * Blizzard's guild tabard emblems (bundled under public/tabard by `pnpm emblems:fetch`). Blizzard gives them ids
 * only; the names and search words here are ours, for the admin picker.
 */
export interface CrestEmblem {
  id: number;
  name: string;
  tags: string[];
}

/** Names and search words by emblem id. Keep in step with the manifest (a test checks every id has one). */
const EMBLEM_NAMES: Record<number, [string, string?]> = {
  0: ["Laurel wreath", "victory leaves"],
  1: ["Goggles", "engineer gnome"],
  2: ["Beetle", "bug insect scarab"],
  3: ["Four-leaf clover", "luck shamrock"],
  4: ["Club", "cards suit"],
  5: ["Spade", "cards suit"],
  6: ["Heart", "cards suit love"],
  7: ["Diamond", "cards suit"],
  8: ["Compass rose", "star navigation"],
  9: ["Coronet", "crown royal"],
  10: ["Open crown", "royal"],
  11: ["Royal crown", "king queen"],
  12: ["Double-headed eagle", "bird griffin"],
  13: ["Rampant wolves", "beasts pair"],
  14: ["Lion face", "cat beast"],
  15: ["Butterfly", "insect moth"],
  16: ["Anchor", "sea ship sailor"],
  17: ["Ship", "sea sail boat"],
  18: ["Lily", "flower fleur-de-lis"],
  19: ["Leaf", "plant herb"],
  20: ["Gears", "cog engineer"],
  21: ["Flame", "fire"],
  22: ["Hammer", "warhammer smith"],
  23: ["Battle axe", "weapon"],
  24: ["Skull", "death bone"],
  25: ["Winged helm", "valkyrie warrior"],
  26: ["Coin purse", "gold money pouch"],
  27: ["Ring", "band gold"],
  28: ["Potions", "alchemy flask"],
  29: ["Anvil", "smith forge"],
  30: ["Mask", "masquerade rogue"],
  31: ["Crossbow", "bow hunter"],
  32: ["Open book", "tome lore"],
  33: ["Jester hat", "fool"],
  34: ["Tree", "oak forest"],
  35: ["Chalice", "goblet grail cup"],
  36: ["Cobra", "snake serpent"],
  37: ["Serpents", "snakes pair"],
  38: ["Shield and sword", "warrior defender"],
  39: ["Dagger", "blade knife rogue"],
  40: ["Skull and daggers", "death rogue"],
  41: ["Totem", "troll tiki"],
  42: ["Wyvern", "dragon bat"],
  43: ["Horned demon", "fiend devil"],
  44: ["Ram", "goat horns"],
  45: ["Boots", "travel"],
  46: ["Fur boots", "winter"],
  47: ["Scallop shell", "sea pilgrim"],
  48: ["Watching eyes", "eyes"],
  49: ["Candle", "light wax"],
  50: ["Top hat", "gentleman"],
  51: ["Lantern", "light hive"],
  52: ["Bell", "chime"],
  53: ["Padlock", "lock"],
  54: ["Saltire", "crossed bands x"],
  55: ["Scissors", "tailor"],
  56: ["Wizard hat", "mage"],
  57: ["Cauldron", "witch brew"],
  58: ["Mountain", "peak"],
  59: ["Mushroom", "fungus"],
  60: ["Dead tree", "withered"],
  61: ["Trefoil knot", "triangle"],
  62: ["Spiked star", "throwing star snowflake"],
  63: ["Chevron down", "stripe"],
  64: ["Chevron up", "stripe"],
  65: ["Cockroach", "bug insect"],
  66: ["Drumstick", "meat food"],
  67: ["Muffin", "food cake"],
  68: ["Soup bowl", "food stew"],
  69: ["Roaring bear", "beast"],
  70: ["Rib cage", "bones undead"],
  71: ["Scarecrow", "farm"],
  72: ["Playing cards", "gamble"],
  73: ["Lobster", "sea crustacean"],
  74: ["Daisy", "flower"],
  75: ["Beer mugs", "ale tavern drink"],
  76: ["Key", "lock"],
  77: ["Cat face", "kitty"],
  78: ["Monkey", "ape"],
  79: ["Content cat", "kitty"],
  80: ["Lizard", "salamander"],
  81: ["Wrench", "tool engineer"],
  82: ["Eye", "watch"],
  83: ["Wheel", "cart"],
  84: ["Bat", "night"],
  85: ["Hourglass", "time sand"],
  86: ["Poison", "flask skull"],
  87: ["Stag", "deer antlers"],
  88: ["Acorn", "oak nut"],
  89: ["Cairn", "stones storm"],
  90: ["Coin stacks", "gold money"],
  91: ["Owl", "bird wisdom"],
  92: ["Skull and crossbones", "pirate death"],
  93: ["Torch", "fire light"],
  94: ["Tombstone", "grave undead"],
  95: ["Water drop", "rain"],
  96: ["Gem", "jewel diamond"],
  97: ["Cross", "cross pattee holy"],
  98: ["Infinity", "eternal"],
  99: ["Moon and stars", "night crescent"],
  100: ["Sunburst", "sun rays"],
  101: ["Paw print", "pet beast"],
  102: ["Bear claw", "beast"],
  103: ["Dragon eye", "eye"],
  104: ["Spiral", "vortex target"],
  105: ["Fel flames", "fire"],
  106: ["Fangs", "jaws teeth"],
  107: ["Horned hand", "rock"],
  108: ["Fist", "strength"],
  109: ["Checkerboard", "chess"],
  110: ["Maple leaf", "leaf"],
  111: ["Burning sun", "fire"],
  112: ["Blasted tree", "fire"],
  113: ["Bull", "horns"],
  114: ["Octopus", "sea kraken"],
  115: ["Tower", "castle keep"],
  116: ["Crossed mallets", "hammers"],
  117: ["Crossed warhammers", "hammers"],
  118: ["Crossed arrows", "hunter"],
  119: ["Crossed swords", "blades"],
  120: ["Crossed axes", "axes"],
  121: ["Crossed scythes", "sickles reaper"],
  122: ["Spiked knuckles", "brawler"],
  123: ["Clawed gauntlets", "claws"],
  124: ["Morning star", "mace"],
  125: ["Pawn", "chess"],
  126: ["Lightning", "storm bolt"],
  127: ["Mushroom cloud", "explosion"],
  128: ["Lion", "mane roar cat"],
  129: ["Gnome", "engineer"],
  130: ["Pine tree", "evergreen forest"],
  131: ["Dynamite", "explosives"],
  132: ["Spider web", "web"],
  133: ["Spider", "arachnid"],
  134: ["Snowflake", "ice frost winter"],
  135: ["Turtle", "tortoise"],
  136: ["Yeti", "beast"],
  137: ["Feather", "quill"],
  138: ["Hooded figure", "cloak"],
  139: ["Horned beast", "claws"],
  140: ["Amulet", "necklace"],
  141: ["Twin serpents", "caduceus snakes"],
  142: ["Pirate hat", "skull"],
  143: ["Scroll", "parchment"],
  144: ["Open scroll", "parchment"],
  145: ["Rabbit", "bunny hare"],
  146: ["Frog", "toad"],
  147: ["Footprint", "foot"],
  148: ["Barrel", "keg ale"],
  149: ["Toadstool", "mushroom"],
  150: ["Omega", "horseshoe"],
  151: ["Horseshoe", "luck"],
  152: ["Flask", "potion"],
  153: ["Shaggy beast", "fur"],
  154: ["Starfish", "star sea"],
  155: ["Clouds", "smoke swirl"],
  156: ["Knotwork", "ornament"],
  157: ["Stone face", "statue"],
  158: ["Lotus", "flower"],
  159: ["Winged heart", "heart"],
  160: ["Guardian lion", "pandaren"],
  161: ["Oni mask", "demon"],
  162: ["Temple guardian", "pandaren mask"],
  163: ["Tribal horns", "sigil"],
  164: ["Horned sigil", "tribal"],
  165: ["Crowned skull", "death"],
  166: ["Chaos star", "arrows"],
  167: ["Demon grin", "fiend"],
  168: ["Beast mask", "wolf"],
  169: ["Horned skull", "bull"],
  170: ["Hooded rogue", "assassin"],
  171: ["Celtic knot", "triquetra"],
  172: ["Ornament", "sigil"],
  173: ["Phoenix", "bird fire"],
  174: ["Goblin", "gold money"],
  175: ["Sceptre", "staff"],
  176: ["Trophy", "cup urn"],
  177: ["Demon skull", "death"],
  178: ["Blossom", "flower bud"],
  179: ["Rainbow", "clouds"],
  180: ["Carved mask", "tribal"],
  181: ["Wolves and moon", "howl"],
  182: ["Melted candle", "wax"],
  183: ["Octagon seal", "bagua"],
  184: ["Rook", "chess castle"],
  185: ["Gift", "present"],
  186: ["Gingerbread man", "cookie"],
  187: ["Murloc", "fish"],
  188: ["Tankards", "ale beer drink"],
  189: ["Wings", "angel"],
  190: ["Claw marks", "scratch"],
  191: ["Swept wings", "feathers"],
  192: ["Dragon skull", "dragon"],
  193: ["Wolf", "howl beast pack"],
  194: ["Seer's eye", "eye"],
  195: ["Rune", "sigil"],
};

export const CREST_EMBLEMS: readonly CrestEmblem[] = CREST_MANIFEST.emblems.map(({ id }) => {
  const [name, tags] = EMBLEM_NAMES[id] ?? [`Emblem ${id}`];
  return { id, name, tags: tags ? tags.split(" ") : [] };
});

const EMBLEM_IDS = new Set<number>(CREST_MANIFEST.emblems.map((e) => e.id));
const EMBLEM_SHA = new Map<number, string>(CREST_MANIFEST.emblems.map((e) => [e.id, e.sha]));

export const isCrestEmblem = (id: number | null | undefined): id is number => id != null && EMBLEM_IDS.has(id);
export const crestEmblem = (id: number) => CREST_EMBLEMS.find((e) => e.id === id);

/** Public URLs of the bundled masks, versioned by content so a refetched image busts caches. */
export const emblemSrc = (id: number) => `/tabard/emblems/${id}.png?v=${EMBLEM_SHA.get(id) ?? ""}`;
/** Paths under public/ for the server, which tints the masks itself. */
export const emblemFile = (id: number) => `tabard/emblems/${id}.png`;

/**
 * The closest Blizzard emblem to each drawn emblem guilds had before real emblems were bundled. Migration 0018 moved
 * every guild onto these (drizzle/0018_guild_crest.sql, kept in step by a test); anything else became the lion (128).
 */
export const LEGACY_EMBLEM_MATCH: Record<string, number> = {
  "cross-pattee": 97,
  cross: 97,
  "cross-fleury": 97,
  "celtic-cross": 171,
  sword: 39,
  "crossed-swords": 119,
  shield: 38,
  lion: 128,
  eagle: 12,
  dragon: 42,
  wolf: 193,
  skull: 24,
  tree: 34,
  sun: 100,
  moon: 99,
  star: 8,
  crown: 11,
  flame: 21,
  axe: 23,
  hammer: 22,
  bow: 31,
  anvil: 29,
  book: 32,
  raven: 91,
  "fleur-de-lis": 18,
  rose: 74,
  keys: 76,
  chalice: 35,
  tower: 115,
  griffin: 12,
};

